do88y/nDaysChallenge

- src/main/java/challenge/nDaysChallenge/domain/Dajim.java
- src/main/java/challenge/nDaysChallenge/domain/Dajim_comment.java
- src/main/java/challenge/nDaysChallenge/domain/Like.java
- src/main/java/challenge/nDaysChallenge/domain/Report.java
> Dajim, Dajim_comment, Like, Report 클래스 수정 및 매핑

- src/main/java/challenge/nDaysChallenge/domain/Dajim.java
- src/main/java/challenge/nDaysChallenge/domain/DajimComment.java
Dajim, DajimComment 엔티티 클래스  수정
> Dajim, DajimComment 엔티티 클래스  수정

- src/main/java/challenge/nDaysChallenge/domain/Dajim.java
- src/main/java/challenge/nDaysChallenge/domain/DajimComment.java
- src/main/resources/application-mysql.yml
- src/main/resources/application-oauth.yml
- src/main/resources/application.properties
- src/main/resources/application.yml
Spring Security, Oauth, jwt 설정 파일 업데이트
> Spring Security, Oauth, jwt 설정 파일 업데이트

- src/main/java/challenge/nDaysChallenge/controller/RoomController.java
- src/main/java/challenge/nDaysChallenge/domain/Member.java
- src/main/java/challenge/nDaysChallenge/domain/RoomMember.java
- src/main/java/challenge/nDaysChallenge/domain/room/GroupRoom.java
- src/main/java/challenge/nDaysChallenge/domain/room/Room.java
- src/main/java/challenge/nDaysChallenge/domain/room/SingleRoom.java
- src/main/java/challenge/nDaysChallenge/service/RoomService.java
- src/test/java/challenge/nDaysChallenge/service/RoomServiceTest.java
> RoomService에 개인, 단체 챌린지 생성 코드 작성 완료

- src/main/java/challenge/nDaysChallenge/controller/RoomController.java
- src/main/java/challenge/nDaysChallenge/controller/dajim/DajimFeedController.java
- src/main/java/challenge/nDaysChallenge/domain/BaseEntity.java
- src/main/java/challenge/nDaysChallenge/domain/Member.java
- src/main/java/challenge/nDaysChallenge/domain/RoomMember.java
- src/main/java/challenge/nDaysChallenge/domain/room/GroupRoom.java
- src/main/java/challenge/nDaysChallenge/domain/room/Room.java
- src/main/java/challenge/nDaysChallenge/domain/room/RoomType.java
- src/main/java/challenge/nDaysChallenge/domain/room/SingleRoom.java
- src/main/java/challenge/nDaysChallenge/dto/request/DajimCommentRequestDto.java
- src/main/java/challenge/nDaysChallenge/dto/request/LikesRequestDto.java
- src/main/java/challenge/nDaysChallenge/dto/response/DajimCommentResponseDto.java
- src/main/java/challenge/nDaysChallenge/dto/response/LikesResponseDto.java
- src/main/java/challenge/nDaysChallenge/dto/response/dajimCommentsResponseDto.java
- src/main/java/challenge/nDaysChallenge/repository/MemberRepository.java
- src/main/java/challenge/nDaysChallenge/repository/RoomMemberRepository.java
- src/main/java/challenge/nDaysChallenge/repository/dajim/DajimFeedRepository.java
- src/main/java/challenge/nDaysChallenge/repository/room/GroupRoomRepository.java
- src/main/java/challenge/nDaysChallenge/repository/room/RoomRepository.java
- src/main/java/challenge/nDaysChallenge/service/RoomService.java
- src/main/java/challenge/nDaysChallenge/service/dajim/DajimFeedService.java
- src/test/java/challenge/nDaysChallenge/service/RoomServiceTest.java
count 컬럼이 RoomMember에 있어서 개인 챌린지 숫자를 세지 못하는 문제 해결해야 함
> 챌린지 생성 수정 중

- src/main/java/challenge/nDaysChallenge/controller/dajim/DajimController.java
- src/main/java/challenge/nDaysChallenge/domain/Member.java
- src/main/java/challenge/nDaysChallenge/domain/MemberSignUpDto.java
- src/main/java/challenge/nDaysChallenge/domain/Relationship.java
- src/main/java/challenge/nDaysChallenge/domain/dajim/Dajim.java
- src/main/java/challenge/nDaysChallenge/domain/dajim/Emotion.java
- src/main/java/challenge/nDaysChallenge/dto/request/DajimRequestDto.java
- src/main/java/challenge/nDaysChallenge/dto/response/DajimResponseDto.java
- src/main/java/challenge/nDaysChallenge/repository/MemberRepository.java
- src/main/java/challenge/nDaysChallenge/repository/dajim/DajimRepository.java
- src/main/java/challenge/nDaysChallenge/service/dajim/DajimService.java
- src/main/resources/application-mysql.yml
- src/test/java/challenge/nDaysChallenge/dajim/DajimTest.java
- src/test/java/challenge/nDaysChallenge/service/RoomServiceTest.java
다짐 수정 메소드 추가 및 다짐 업로드, 수정 테스트 완료
> 다짐 수정 메소드 추가 및 다짐 업로드, 수정 테스트 완료

- src/main/java/challenge/nDaysChallenge/controller/RoomController.java
- src/main/java/challenge/nDaysChallenge/dto/request/RoomRequestDTO.java
- src/main/java/challenge/nDaysChallenge/repository/RoomMemberRepository.java
- src/main/java/challenge/nDaysChallenge/repository/room/GroupRoomRepository.java
- src/main/java/challenge/nDaysChallenge/repository/room/RoomRepository.java
- src/main/java/challenge/nDaysChallenge/repository/room/SingleRoomRepository.java
- src/main/java/challenge/nDaysChallenge/service/RoomService.java
- src/main/resources/application-mysql.yml
- src/test/java/challenge/nDaysChallenge/service/RoomServiceTest.java
테스트 시 카멜케이스로 테이블이 만들어지길래 설정을 보니 잘못 설정되어 있어서 변경했습니다.
> hibernate physical-starategy 언더바 케이스로 변경

- src/main/java/challenge/nDaysChallenge/controller/AuthController.java
- src/main/java/challenge/nDaysChallenge/controller/MemberController.java
- src/main/java/challenge/nDaysChallenge/controller/RelationshipController.java
- src/main/java/challenge/nDaysChallenge/controller/RoomController.java
- src/main/java/challenge/nDaysChallenge/controller/dajim/DajimController.java
- src/main/java/challenge/nDaysChallenge/domain/Member.java
- src/main/java/challenge/nDaysChallenge/dto/request/DajimRequestDto.java
- src/main/java/challenge/nDaysChallenge/dto/request/MemberEditRequestDto.java
- src/main/java/challenge/nDaysChallenge/dto/request/MemberRequestDto.java
- src/main/java/challenge/nDaysChallenge/dto/response/MemberInfoResponseDto.java
- src/main/java/challenge/nDaysChallenge/repository/MemberRepository.java
- src/main/java/challenge/nDaysChallenge/repository/room/RoomRepository.java
- src/main/java/challenge/nDaysChallenge/service/MemberService.java
- src/main/java/challenge/nDaysChallenge/service/RoomService.java
- src/main/java/challenge/nDaysChallenge/service/dajim/DajimService.java
- src/main/resources/application-mysql.yml
- src/test/java/challenge/nDaysChallenge/dajim/DajimFeedRepositoryTest.java
- src/test/java/challenge/nDaysChallenge/dajim/DajimRepositoryTest.java
> 다짐 등록, 수정 메소드 통합

- src/main/java/challenge/nDaysChallenge/controller/MemberController.java
- src/main/java/challenge/nDaysChallenge/dto/request/DajimRequestDto.java
- src/main/java/challenge/nDaysChallenge/dto/request/EmotionRequestDto.java
- src/main/java/challenge/nDaysChallenge/dto/request/MemberEditRequestDto.java
- src/main/java/challenge/nDaysChallenge/dto/request/MemberRequestDto.java
- src/main/resources/application-mysql.yml
- src/test/java/challenge/nDaysChallenge/jwt/feed.http
> Dto 기본 생성자 누락 수정

- .gitignore
- src/main/java/challenge/nDaysChallenge/config/SecurityConfig.java
- src/main/java/challenge/nDaysChallenge/controller/MemberController.java
- src/main/java/challenge/nDaysChallenge/controller/RoomController.java
- src/main/java/challenge/nDaysChallenge/domain/Member.java
- src/main/java/challenge/nDaysChallenge/domain/dajim/Dajim.java
- src/main/java/challenge/nDaysChallenge/domain/dajim/Emotion.java
- src/main/java/challenge/nDaysChallenge/dto/request/LoginRequestDto.java
- src/main/java/challenge/nDaysChallenge/jwt/JwtFilter.java
- src/main/java/challenge/nDaysChallenge/jwt/TokenProvider.java
- src/main/java/challenge/nDaysChallenge/repository/MemberRepository.java
- src/main/java/challenge/nDaysChallenge/repository/dajim/DajimRepository.java
- src/main/java/challenge/nDaysChallenge/repository/dajim/EmotionRepository.java
- src/main/java/challenge/nDaysChallenge/service/AuthService.java
- src/main/java/challenge/nDaysChallenge/service/MemberService.java
- src/main/java/challenge/nDaysChallenge/service/RoomService.java
- src/main/java/challenge/nDaysChallenge/service/dajim/DajimFeedService.java
- src/main/java/challenge/nDaysChallenge/service/dajim/DajimService.java
- src/main/java/challenge/nDaysChallenge/service/dajim/EmotionService.java
- src/main/resources/application-mysql.yml
- src/main/resources/application-prod.yaml
- src/test/java/challenge/nDaysChallenge/dajim/DajimFeedRepositoryTest.java
- src/test/java/challenge/nDaysChallenge/dajim/QueryTest.java
- emotion 도메인 로직 정리 (엔티티에 update 메소드 추가, 이모션 등록 시 dajim의 addEmotions 리스트에 넣는 로직 추가)
- 쿼리 테스트 완료
- 기타 코드 정리
> emotion 도메인 수정, 쿼리 테스트

- src/main/java/challenge/nDaysChallenge/controller/dajim/DajimFeedController.java
- src/main/java/challenge/nDaysChallenge/jwt/RefreshToken.java
- src/main/java/challenge/nDaysChallenge/jwt/TokenProvider.java
- src/main/java/challenge/nDaysChallenge/repository/dajim/DajimFeedRepository.java
- src/main/java/challenge/nDaysChallenge/service/dajim/DajimFeedService.java
- src/main/resources/application.yml
- src/test/java/challenge/nDaysChallenge/dajim/DajimFeedRepositoryTest.java
- 리프레쉬토큰 중 updatedDate 컬럼 삭제, createdDate만 유지 (만료 시 재발급 대신 뷰에서 재로그인 요청하도록 로직 변경함)
- 피드 도메인 수정 (피드에는 공개 설정된 다짐들만 올라가도록 함 - 본인 다짐에도 똑같이 적용)
> 리프레쉬토큰 코드 수정, 피드 도메인 수정

- src/main/java/challenge/nDaysChallenge/config/SecurityConfig.java
> allowedorigin 주소 변경

- .gitignore
- src/main/java/challenge/nDaysChallenge/controller/ReportController.java
- src/main/java/challenge/nDaysChallenge/controller/RoomController.java
- src/main/java/challenge/nDaysChallenge/domain/Report.java
- src/main/java/challenge/nDaysChallenge/domain/RoomMember.java
- src/main/java/challenge/nDaysChallenge/domain/room/GroupRoom.java
- src/main/java/challenge/nDaysChallenge/domain/room/Room.java
- src/main/java/challenge/nDaysChallenge/domain/room/SingleRoom.java
- src/main/java/challenge/nDaysChallenge/dto/request/ReportRequestDto.java
- src/main/java/challenge/nDaysChallenge/dto/request/Room/GroupRoomRequestDto.java
- src/main/java/challenge/nDaysChallenge/dto/request/Room/RoomRequestDto.java
- src/main/java/challenge/nDaysChallenge/dto/response/ReportResponseDto.java
- src/main/java/challenge/nDaysChallenge/repository/ReportRepository.java
- src/main/java/challenge/nDaysChallenge/service/ReportService.java
- src/main/java/challenge/nDaysChallenge/service/RoomService.java
- src/main/resources/application-mysql.yml
- src/test/java/challenge/nDaysChallenge/Room/RoomQueryTest.java
- src/test/java/challenge/nDaysChallenge/Room/RoomServiceTest.java
- src/test/java/challenge/nDaysChallenge/Room/createRoom.http
- src/test/java/challenge/nDaysChallenge/report/ReportServiceTest.java
> 챌린지 상태 변경 및 신고 기능 추가

- src/main/java/challenge/nDaysChallenge/domain/Member.java
- src/test/java/challenge/nDaysChallenge/member/memberTest.java
- 오류로 인해 멤버 엔티티 유니크 제약조건 임시 삭제
- (멤버 삭제 오류로 테스트 진행 중)
> 멤버 엔티티 유니크 제약조건 삭제

- src/main/java/challenge/nDaysChallenge/controller/RoomController.java
- src/main/java/challenge/nDaysChallenge/domain/Stamp.java
- src/main/java/challenge/nDaysChallenge/dto/request/StampDto.java
- src/main/java/challenge/nDaysChallenge/service/RoomService.java
- src/test/java/challenge/nDaysChallenge/Room/RoomServiceTest.java
- 기존 날짜별로 day 컬럼 생성하는 코드에서 day 컬럼 하나에 String으로 추가해 가는 방식으로 변경
> 스탬프 컬럼 day에 String 추가하는 방식으로 변경

- src/main/java/challenge/nDaysChallenge/controller/RelationshipController.java
- src/main/java/challenge/nDaysChallenge/dto/request/FindFriendsRequestDTO.java
- src/main/java/challenge/nDaysChallenge/dto/response/FindFriendsResponseDTO.java
- src/main/java/challenge/nDaysChallenge/service/RelationshipService.java
> 0111 유저검색시 프로필사진도 뜨게 수정

- src/main/java/challenge/nDaysChallenge/dto/request/FindFriendsRequestDTO.java
> 0111FindFriendRequestDTO 수정

- src/main/java/challenge/nDaysChallenge/controller/RoomController.java
- src/main/java/challenge/nDaysChallenge/domain/Stamp.java
- src/main/java/challenge/nDaysChallenge/domain/room/Room.java
- src/main/java/challenge/nDaysChallenge/repository/room/RoomRepository.java
- src/main/java/challenge/nDaysChallenge/service/AdminService.java
- src/main/java/challenge/nDaysChallenge/service/RoomService.java
- src/main/resources/application-mysql.yml
- src/test/java/challenge/nDaysChallenge/Room/RoomServiceTest.java
- src/test/java/challenge/nDaysChallenge/Room/awsRoomTest.http
- src/test/java/challenge/nDaysChallenge/Room/createRoom.http
- roomRepository의 findById를 findByNumber로 수정
- 그룹 챌린지 스탬프 key값 저장을 ID에서 nickname으로 변경
> Style: roomRepository의 findById를 findByNumber로 수정

- .github/workflows/deploy.yml
set-output 코드 deprecate되어 설정 변경 중
> deploy.yml deprecated 설정 변경 중

- .github/workflows/deploy.yml
> deprecated 코드 변경 중

- .ebextensions/00-makeFiles.config
- .github/workflows/deploy.yml
- .platform/nginx/nginx.conf
> github action 배포 자동화 설정

- Procfile
> github action 배포 자동화 설정 추가

- .github/workflows/deploy.yml
- github action 설정 빌드 후 EB 상태 심각으로 변화해 코드 수정 중
> github action 오류 해결 중

- .github/workflows/deploy.yml
- 버전 갱신 시 날짜, 시간 추가되도록 설정했으나 작동하지 않아 수정
> github action 버전 날짜 추가 코드 수정

- .github/workflows/deploy.yml
- 빌드 시 깃허브에 제외된 application.properties, application-prod.properties 파일 따로 생성하도록 설정
> github action application.yml 관련 설정 추가

- .github/workflows/deploy.yml
github action bad substitution 오류 해결 중
> github action bad substitution 오류 해결 중

- .github/workflows/deploy.yml
> github action 배포 자동화 오류 해결 중

- .github/workflows/deploy.yml
> deploy.yml 버전 날짜 코드 수정

- .github/workflows/deploy.yml
- nginx.conf 에서 서버 5000포트로 설정 변경 후 elastic beanstalk 환경 status ok로 변경됨
- 깃허브 actions에서는 deployment fail로 출력돼 현재 확인 중
> eb deploy 오류 해결 확인 중

- .github/workflows/deploy.yml
- .platform/nginx/nginx.conf
- src/main/resources/application-mysql.yml
> nginx.conf 설정 변경

- .github/workflows/deploy.yml
- .platform/nginx/nginx.conf
> github actions 빌드 오류 원인 파악 중

- .platform/nginx/nginx.conf
- src/main/java/challenge/nDaysChallenge/controller/RelationshipController.java
- src/main/java/challenge/nDaysChallenge/domain/member/Member.java
- src/main/java/challenge/nDaysChallenge/service/RelationshipService.java
- src/main/resources/application-mysql.yml
- src/test/java/challenge/nDaysChallenge/Room/createRoom.http
- src/test/java/challenge/nDaysChallenge/auth/AuthTest.http
- src/test/java/challenge/nDaysChallenge/relationship/SearchTest.http
> Relationship 친구검색 오류 해결 중

- src/main/java/challenge/nDaysChallenge/controller/RoomController.java
- src/main/java/challenge/nDaysChallenge/domain/Stamp.java
- src/main/java/challenge/nDaysChallenge/domain/member/Member.java
- src/main/java/challenge/nDaysChallenge/domain/room/GroupRoom.java
- src/main/java/challenge/nDaysChallenge/domain/room/Room.java
- src/main/java/challenge/nDaysChallenge/domain/room/RoomMember.java
- src/main/java/challenge/nDaysChallenge/domain/room/SingleRoom.java
- src/main/java/challenge/nDaysChallenge/repository/room/GroupRoomRepository.java
- src/main/java/challenge/nDaysChallenge/repository/room/SingleRoomRepository.java
- src/main/java/challenge/nDaysChallenge/service/RoomService.java
- src/main/java/challenge/nDaysChallenge/service/member/MemberService.java
- src/main/resources/application-mysql.yml
- src/test/java/challenge/nDaysChallenge/Room/RoomQueryTest.java
- src/test/java/challenge/nDaysChallenge/Room/RoomServiceTest.java
- 게스트 탈퇴 시 groupRoom에서 호스트의 member_number 삭제되는 것 해결해야 함
> memberService 의 멤버 탈퇴 코드에서 groupRoom 관련 오류 수정

- src/main/java/challenge/nDaysChallenge/controller/RelationshipController.java
- src/main/java/challenge/nDaysChallenge/domain/member/Member.java
- src/main/resources/application-mysql.yml
- src/test/java/challenge/nDaysChallenge/auth/AuthTest.http
- src/test/java/challenge/nDaysChallenge/relationship/SearchTest.http
> RequestParam 재수정

- src/main/java/challenge/nDaysChallenge/controller/RelationshipController.java
- src/main/java/challenge/nDaysChallenge/domain/dajim/Dajim.java
- src/main/java/challenge/nDaysChallenge/domain/member/Member.java
- src/test/java/challenge/nDaysChallenge/auth/AuthTest.http
- src/test/java/challenge/nDaysChallenge/relationship/SearchTest.http
> RequestParam 설정 수정

- src/main/java/challenge/nDaysChallenge/controller/RelationshipController.java
- src/main/java/challenge/nDaysChallenge/service/RelationshipService.java
- src/test/java/challenge/nDaysChallenge/Room/RoomQueryTest.java
- src/test/java/challenge/nDaysChallenge/Room/RoomServiceTest.java
- src/test/java/challenge/nDaysChallenge/auth/AuthTest.http
- src/test/java/challenge/nDaysChallenge/dajim/DajimRepositoryTest.java
- src/test/java/challenge/nDaysChallenge/dajim/DajimServiceTest.java
- src/test/java/challenge/nDaysChallenge/emotion/EmotionRepositoryTest.java
- src/test/java/challenge/nDaysChallenge/emotion/EmotionServiceTest.java
- src/test/java/challenge/nDaysChallenge/relationship/RelationshipControllerTest.java
- src/test/java/challenge/nDaysChallenge/relationship/SearchTest.http
- src/test/java/challenge/nDaysChallenge/report/ReportServiceTest.java
- src/test/java/challenge/nDaysChallenge/security/WithUserDetailsTest.java
- 친구 검색 메소드 수정 완료
- defaultValue 설정 추가
- 멤버 빌더 설정 변경
- List에 Builder.Default 추가해 null 초기화 방지
> 친구 검색 메소드 수정 완료 및 멤버 빌더 설정 변경

- .github/workflows/deploy.yml
- src/main/java/challenge/nDaysChallenge/config/SecurityConfig.java
- 배포 설정 변경
- 특정 브랜치  커밋 시 배포하는 조건 삭제
- 쿠키 허용
- local storage에서 http-only 쿠키 저장소로 변경함에 따라 설정 허용
> 배포 및 쿠키 허용 설정 변경

- src/main/java/challenge/nDaysChallenge/dto/response/jwt/TokenResponseDto.java
- src/main/java/challenge/nDaysChallenge/jwt/TokenProvider.java
- src/main/java/challenge/nDaysChallenge/service/dajim/DajimFeedService.java
- src/main/java/challenge/nDaysChallenge/service/member/MemberService.java
- src/test/java/challenge/nDaysChallenge/auth/AuthServiceTest.java
- src/test/java/challenge/nDaysChallenge/auth/AuthTest.http
- src/test/java/challenge/nDaysChallenge/dajim/DajimServiceTest.java
- src/test/java/challenge/nDaysChallenge/member/MemberServiceTest.java
- 로그인 시 리프레시 토큰 유효기간도 전달하도록 TokenResponseDto 수정
- 서비스 로직 변경 반영한 테스트 수정
> 토큰 dto 및 서비스 테스트 수정

- src/main/java/challenge/nDaysChallenge/service/member/MemberService.java
MemberService 클래스 내 누락된 entitymanager 재주입
> MemberService 클래스 내 누락된 entitymanager 재주입

- .github/workflows/deploy.yml
- main, develop 브랜치로 푸쉬할 때 반영되도록 설정
> github actions 푸쉬 브랜치 설정 변경

- src/main/java/challenge/nDaysChallenge/controller/AdminController.java
- src/main/java/challenge/nDaysChallenge/domain/room/GroupRoom.java
- src/main/java/challenge/nDaysChallenge/dto/request/Room/DeleteRoomRequestDto.java
- src/main/java/challenge/nDaysChallenge/repository/room/GroupRoomRepository.java
- src/main/java/challenge/nDaysChallenge/repository/room/SingleRoomRepository.java
- src/main/java/challenge/nDaysChallenge/service/member/MemberService.java
- src/test/java/challenge/nDaysChallenge/member/MemberServiceTest.java
npe 피하기 위해 객체를 equals 앞에 두고 getter를 뒤에 뒀음.
groupRoom 생성 시 stamp 데이터가 입력되지 않아 guestConnection 메서드는 삭제.
> fix: 방장 외 멤버 탈퇴 시 npe 문제 해결

- .github/workflows/deploy.yml
> fix: 배포 브랜치 설정 변경

- src/main/java/challenge/nDaysChallenge/NDaysChallengeApplication.java
- src/main/java/challenge/nDaysChallenge/config/SecurityConfig.java
- src/test/java/challenge/nDaysChallenge/security/AdminTest.http
사용하는 시큐리티 설정만 추가 (@EnableGlobalMethodSecurity(securedEnabled = true))
> fix : 시큐리티 어노테이션 수정 (배포 오류 원인 찾는 중)

- src/main/java/challenge/nDaysChallenge/service/member/MemberService.java
- src/test/java/challenge/nDaysChallenge/member/MemberServiceTest.java
- src/test/java/challenge/nDaysChallenge/member/MemberTest.http
- 검증 메소드 분리
- 회원 탈퇴 메소드
- 회원과 연관된 엔티티 관련 메소드 따로 분리해 리팩토링
> refactor: Member 도메인 관심사 분리

- src/main/java/challenge/nDaysChallenge/dto/request/member/MemberRequestDto.java
- src/main/java/challenge/nDaysChallenge/service/jwt/AuthService.java
- src/test/java/challenge/nDaysChallenge/auth/AuthTest.http
- 비밀번호, 닉네임 글자수 제한
- 비밀번호 정규표현식 설정
> refactor: 회원가입 유효성 검사 추가

- build.gradle
- src/main/java/challenge/nDaysChallenge/dto/response/jwt/TokenResponseDto.java
- src/main/java/challenge/nDaysChallenge/jwt/RefreshToken.java
- src/main/java/challenge/nDaysChallenge/jwt/TokenProvider.java
- src/main/java/challenge/nDaysChallenge/repository/jwt/RefreshTokenRepository.java
- src/main/java/challenge/nDaysChallenge/service/jwt/AuthService.java
- src/test/java/challenge/nDaysChallenge/auth/AuthTest.http
- 리프레시 토큰 저장소 Redis로 변경
- 빠른 액세스 속도, 편리한 유효기간 설정 등의 장점
> refactor: 리프레시 토큰 DB 이관 (MySQL -> Redis)

- src/main/java/challenge/nDaysChallenge/exception/CommonError.java
- src/main/java/challenge/nDaysChallenge/exception/CustomError.java
- src/main/java/challenge/nDaysChallenge/exception/CustomException.java
- src/main/java/challenge/nDaysChallenge/exception/ErrorCode.java
- src/main/java/challenge/nDaysChallenge/exception/ErrorResponse.java
- src/main/java/challenge/nDaysChallenge/exception/ExceptionHandler.java
- src/main/java/challenge/nDaysChallenge/service/dajim/DajimFeedService.java
- src/main/java/challenge/nDaysChallenge/service/dajim/DajimService.java
- src/main/java/challenge/nDaysChallenge/service/dajim/EmotionService.java
- src/main/java/challenge/nDaysChallenge/service/jwt/AuthService.java
- src/main/java/challenge/nDaysChallenge/service/jwt/CustomUserDetailsService.java
- src/main/java/challenge/nDaysChallenge/service/member/MemberService.java
- src/test/java/challenge/nDaysChallenge/auth/AuthTest.http
- src/test/java/challenge/nDaysChallenge/dajim/DajimTest.http
- src/test/java/challenge/nDaysChallenge/member/MemberTest.http
- @RestControllerAdvice 클래스로 전역 예외 처리 설정 (미완) 
- 커스텀 예외 추가
> refactor: 전역 예외 설정 추가 (진행 중)

- src/main/java/challenge/nDaysChallenge/exception/ExceptionHandler.java
- 500, 400 등 표준 예외 외에도 서비스 로직 관련 커스텀 예외 설정 완료
- 오류 코드, 메시지 전달하도록 설정
- 유효성 검사 오류의 경우 발생 사유 자세히 출력되도록 설정
> refactor: custom exception 업데이트 완료

- .github/workflows/deploy.yml
- .platform/nginx/nginx.conf
- build.gradle
- src/main/java/challenge/nDaysChallenge/exception/ErrorResponse.java
refactor: aws 프리티어 만료로 인한 배포 관련 설정 주석 처리
> refactor: aws 프리티어 만료로 인한 배포 관련 설정 주석 처리
